# Generated by Django 5.1.3 on 2024-11-30 21:45

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eccomerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
